# Generated by Django 5.2.6 on 2025-09-09 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ci',
            field=models.CharField(blank=True, help_text='Cédula de identidad sin guiones ni puntos', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,10}$', 'CI debe tener entre 7-10 dígitos')], verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'Teléfono debe tener 7-8 dígitos')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'Teléfono debe tener 7-8 dígitos')], verbose_name='Teléfono contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Ej: Madre, Esposo, Hermana, etc.', max_length=50, verbose_name='Parentesco'),
        ),
    ]
